#Iron Chests Default Files
#Setting a value will recopy the default files.
#Tue Aug 04 22:17:57 EDT 2026
=\=\=\=\=\=\=
barrels=true
chests=true
>>>>>>>=Stashed changes
chest_upgrades=true
<<<<<<<=Updated upstream
