#Iron Chests Default Files
#Setting a value will recopy the default files.
#Sun May 17 13:27:15 PDT 2026
=\=\=\=\=\=\=
barrels=true
chests=true
>>>>>>>=Stashed changes
chest_upgrades=true
<<<<<<<=Updated upstream
