#Iron Chests Default Files
#Setting a value will recopy the default files.
#Sat May 09 21:12:42 PDT 2026
=\=\=\=\=\=\=
barrels=true
chests=true
>>>>>>>=Stashed changes
chest_upgrades=true
<<<<<<<=Updated upstream
