// Listen to item tag event
ServerEvents.tags('item', event => {

  // Get tag collection and remove an item from it
  event.remove('forge:ores/silver', 'spelunkery:granite_silver_ore')
  event.remove('forge:ores/silver', 'spelunkery:diorite_silver_ore')
  event.remove('forge:ores/silver', 'spelunkery:andesite_silver_ore')
  event.remove('forge:ores/silver', 'spelunkery:tuff_silver_ore')
  event.remove('forge:ores/lead', 'spelunkery:granite_lead_ore')
  event.remove('forge:ores/lead', 'spelunkery:diorite_lead_ore')
  event.remove('forge:ores/lead', 'spelunkery:andesite_lead_ore')
  event.remove('forge:ores/lead', 'spelunkery:tuff_lead_ore')
  event.remove('forge:ores/zinc', 'spelunkery:granite_zinc_ore')
  event.remove('forge:ores/zinc', 'spelunkery:diorite_zinc_ore')
  event.remove('forge:ores/zinc', 'spelunkery:andesite_zinc_ore')
  event.remove('forge:ores/zinc', 'spelunkery:tuff_zinc_ore')
  event.remove('forge:ores/jade', 'spelunkery:granite_jade_ore')
  event.remove('forge:ores/jade', 'spelunkery:diorite_jade_ore')
  event.remove('forge:ores/jade', 'spelunkery:andesite_jade_ore')
  event.remove('forge:ores/jade', 'spelunkery:tuff_jade_ore')
  event.remove('spelunkery:silver_ores', 'spelunkery:granite_silver_ore')
  event.remove('spelunkery:silver_ores', 'spelunkery:diorite_silver_ore')
  event.remove('spelunkery:silver_ores', 'spelunkery:andesite_silver_ore')
  event.remove('spelunkery:silver_ores', 'spelunkery:tuff_silver_ore')
  event.remove('spelunkery:zinc_ores', 'spelunkery:granite_zinc_ore')
  event.remove('spelunkery:zinc_ores', 'spelunkery:diorite_zinc_ore')
  event.remove('spelunkery:zinc_ores', 'spelunkery:andesite_zinc_ore')
  event.remove('spelunkery:zinc_ores', 'spelunkery:tuff_zinc_ore')
  event.remove('spelunkery:lead_ores', 'spelunkery:granite_lead_ore')
  event.remove('spelunkery:lead_ores', 'spelunkery:diorite_lead_ore')
  event.remove('spelunkery:lead_ores', 'spelunkery:andesite_lead_ore')
  event.remove('spelunkery:lead_ores', 'spelunkery:tuff_lead_ore')
  event.remove('forge:silver_ores', 'spelunkery:granite_silver_ore')
  event.remove('forge:silver_ores', 'spelunkery:diorite_silver_ore')
  event.remove('forge:silver_ores', 'spelunkery:andesite_silver_ore')
  event.remove('forge:silver_ores', 'spelunkery:tuff_silver_ore')
  event.remove('forge:lead_ores', 'spelunkery:granite_lead_ore')
  event.remove('forge:lead_ores', 'spelunkery:diorite_lead_ore')
  event.remove('forge:lead_ores', 'spelunkery:andesite_lead_ore')
  event.remove('forge:lead_ores', 'spelunkery:tuff_lead_ore')
  event.remove('forge:jade_ores', 'spelunkery:granite_jade_ore')
  event.remove('forge:jade_ores', 'spelunkery:diorite_jade_ore')
  event.remove('forge:jade_ores', 'spelunkery:andesite_jade_ore')
  event.remove('forge:jade_ores', 'spelunkery:tuff_jade_ore')
  event.remove('forge:zinc_ores', 'spelunkery:granite_zinc_ore')
  event.remove('forge:zinc_ores', 'spelunkery:diorite_zinc_ore')
  event.remove('forge:zinc_ores', 'spelunkery:andesite_zinc_ore')
  event.remove('forge:zinc_ores', 'spelunkery:tuff_zinc_ore')

  event.remove('forge:weapon/tools/melee', 'minecraft:mace')
  event.remove('forge:tools/mace', 'minecraft:mace')
  event.remove('forge:foods', 'minecraft:ominous_bottle')
  event.remove('forge:discs/music', 'minecraft:music_disc_creator')
  event.remove('forge:discs/music', 'minecraft:music_disc_creator_music_box')
  event.remove('forge:rods/breeze', 'minecraft:breeze_rod')

  event.remove('xkdeco:red_roof', 'xkdeco:red_roof_small_flat_end')
  event.remove('xkdeco:red_roof', 'xkdeco:red_roof_small_ridge_end')
  event.remove('xkdeco:blue_roof', 'xkdeco:blue_roof_small_flat_end')
  event.remove('xkdeco:blue_roof', 'xkdeco:blue_roof_small_ridge_end')
  event.remove('xkdeco:cyan_roof', 'xkdeco:cyan_roof_deco_oblique')
  event.remove('xkdeco:cyan_roof', 'xkdeco:cyan_roof_ridge_end')
  event.remove('xkdeco:cyan_roof', 'xkdeco:cyan_roof_small_flat_end')
  event.remove('xkdeco:cyan_roof', 'xkdeco:cyan_roof_small_ridge_end')
  event.remove('xkdeco:green_roof', 'xkdeco:green_roof_small_flat_end')
  event.remove('xkdeco:green_roof', 'xkdeco:green_roof_small_ridge_end')
  event.remove('xkdeco:yellow_roof', 'xkdeco:yellow_roof_deco_oblique')
  event.remove('xkdeco:yellow_roof', 'xkdeco:yellow_roof_ridge_end')
  event.remove('xkdeco:yellow_roof', 'xkdeco:yellow_roof_small_flat_end')
  event.remove('xkdeco:yellow_roof', 'xkdeco:yellow_roof_small_ridge_end')
  event.remove('xkdeco:black_roof', 'xkdeco:black_roof_deco_oblique')
  event.remove('xkdeco:black_roof', 'xkdeco:black_roof_ridge_end')
  event.remove('xkdeco:black_roof', 'xkdeco:black_roof_small_flat_end')
  event.remove('xkdeco:black_roof', 'xkdeco:black_roof_small_ridge_end')

  // Get tag and remove all entries from it
  event.removeAll('spelunkery:jade_ores')
  event.removeAll('xkdeco:roof_ridge_end')

})