#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 14 17:02:32 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=
enableShaders=true
