#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 10 11:12:25 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
