#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 13 22:46:36 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
